name = "Cobblemon Returns"
author = "Gabriel Afonso"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1d6d6f9dd705e1783dd6871e81800fc12801000d50026b8517c57e772dcd445"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
