name = "Cobblemon Returns"
author = "Gabriel Afonso"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf0bc7bc858a81bea607c4d1acfad36c8309d4ac9f310f47ab14cb209ba518ca"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
